# Machine Learning Math

## Softmax

Softmax is an Activation Functions. Softmax is a generalization of Sigmoind for $n = 2$

<div class="alert alert-block alert-warning">
    TODO:
    <br/>https://www.quora.com/Why-is-it-better-to-use-Softmax-function-than-sigmoid-function 
    <br/>https://gombru.github.io/2018/05/23/cross_entropy_loss/
</div>

## Sigmoid

Sigmoid is an activation function:

$$\sigma(x) = \frac{1}{1 + e^{-x}}$$

The **derivative** of Sigmoid is:

$$
\begin{aligned}
\sigma'(x) = \frac{\mathrm{d}}{\mathrm{d}x} \sigma(x) &= \frac{\mathrm{d}}{\mathrm{d}x} \Big(\frac{1}{1 + e^{-x}} \Big)^{-1} \\[3pt]
&= -(1 + e^{-x})^{-2} \; (-e^{-x}) \\[3pt]
&= \frac{e^{-x}}{(1+e^{-x})^2} \\[3pt]
&= \frac{1}{1+e^{-x}} \cdot \frac{e^{-x}}{1+e^{-x}} \\[3pt]
&= \frac{1}{1+e^{-x}} \cdot \frac{1 + e^{-x} - 1}{1+e^{-x}} \\[3pt]
&= \frac{1}{1+e^{-x}} \cdot \bigg( \frac{1 + e^{-x}}{1+e^{-x}} - \frac{1}{1+e^{-x}} \bigg) \\[3pt]
&= \frac{1}{1+e^{-x}} \cdot \bigg( 1 - \frac{1}{1+e^{-x}} \bigg) \\[3pt]
&= \sigma(x) \cdot \big( 1 - \sigma(x) \big)
\end{aligned}
$$

## Cross Entropy Loss

The network needs to make predictions as close as possible to the real values. To measure this, we use a metric of how wrong the predictions are, the **error**. 

Cross Entropy is used in ML as a **loss function**. Multiclass Cross Entropy is a generalization for Two Class Cross Entropy

<div class="alert alert-block alert-warning">TODO</div>

## Sum of Squared Errors (SSE)

A common metric is the sum of the squared errors. The **SSE** is a good choice for a few reasons, for example compared to just using $E=|y-\hat{y}|$: the square ensures the **error is always positive** and **larger errors are penalized** more than smaller errors. Also, it makes the **math nice**.

$$E = \frac{1}{2} \sum_\mu \sum_j \big[y_j^{\,\mu} - \hat{y}_j^{\,\mu}\big]^2$$

with the **prediction** 

$$\hat{y}_j^{\,\mu} = f \big(\sum_i w_{ij} \, x_i^{\,\mu} \big) = f(h_{\mu j})$$

and the **real value** $y$, the number of **output units** $j$ and the number of **data records** $\mu$. Also let be $h_{\mu j}$ the **linear combination** of the weights and the inputs.

Our goal is to find weights $w_{ij}$ that minimize the squared error $E$. To do this with a neural network we typically use **gradient descent**.

## Gradient Descent of SSE

Weights are updated by **substracting** the **gradient** (or **weight step**) $\Delta w_i$ multiplied by a **learning rate** $\eta$:

$$w_i  = w_i + \Delta w_i = w_i - \eta \, \frac{\partial E}{\partial w_i}$$

### One Output Unit

Supposed we have only **one data record** and **one output unit** then the SSE is

$$E = \frac{1}{2}(y - \hat{y})^2$$

with the **error** $(y - \hat{y})$, 

$$
\begin{aligned}
  \hat{y} &= f(h) = \sigma(h) \\[3pt]
        h &= \sum_i w_i x_i
\end{aligned}
$$

The gradient of $E$ w.r.t. $w_i$ is the negative of the **error** times the **derivative of the activation function** at $h$ times the **input value** $x_i$:

$$
\begin{aligned}
  \frac{\partial E}{\partial w_i} &= \frac{\partial}{\partial w_i} \frac{1}{2} (y - \hat{y})^2 \\[3pt]
                                  &=(y - \hat{y}) \cdot \frac{\partial}{\partial w_i} (y - \hat{y}) \\[3pt]
                                  &=-(y - \hat{y}) \cdot \frac{\partial}{\partial w_i} \hat{y} \\[3pt]
                                  &=-(y - \hat{y}) \cdot f'(h) \cdot \frac{\partial}{\partial w_i}\sum_i w_i x_i \\[3pt]
                                  &=-(y - \hat{y}) \cdot f'(h) \cdot x_i
\end{aligned}
$$

Then the **weight step** $\Delta w_i$ is

$$
\begin{aligned}
  \Delta w_i &= - \eta \, \frac{\partial E}{\partial w_i} \\[3pt]
             &= \eta \cdot (y - \hat{y}) \cdot f'(h) \cdot x_i
\end{aligned}
$$

For convenience we define an **error term** $\delta$ as

$$\delta = (y - \hat{y}) \cdot f'(h)$$

so we can write the **weight update** as

$$
\begin{aligned}
   w_i &= w_i + \Delta w_i \\[2pt]
       &= w_i - \eta \, \frac{\partial E}{\partial w_i} \\[2pt]
       &= w_i + \eta \, \delta \, x_i
\end{aligned}
$$

### Multiple Output Units

for multiple output units we have multiple error terms:

$$\delta_j = (y_j - \hat{y}_j) \cdot f'(h_j)$$

$$w_{ij} = w_{ij} + \Delta w_{ij} = w_{ij} + \eta \, \delta_j \, x_i$$


### Python Example

with one data record and four input values:

In [81]:
import numpy as np
import pandas as pd

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)
w = np.array([0.5, -0.5, 0.3, 0.1])                # Initial weights

data = []
for i in range(6):
    h = np.dot(x, w)
    y_hat = sigmoid(h)
    error = y - y_hat
    data.append((w[0], w[1], w[2], w[3], error))

    error_term = error * sigmoid_prime(h)          # more efficient would be: error_term = error * y_hat * (1 - y_hat)
    delta_w = learnrate * error_term * x
    w = w + delta_w

pd.DataFrame(data, columns=['w1', 'w2', 'w3', 'w4', 'error']).round(4)

w1      w2      w3      w4   error
0  0.5000 -0.5000  0.3000  0.1000 -0.1900
1  0.4797 -0.5406  0.2390  0.0187 -0.0475
2  0.4738 -0.5524  0.2214 -0.0048 -0.0035
3  0.4734 -0.5533  0.2201 -0.0065 -0.0002
4  0.4733 -0.5533  0.2200 -0.0067 -0.0000
5  0.4733 -0.5533  0.2200 -0.0067 -0.0000

## Mean Squared Errors (MSE)

When we're using a **lot of data**, summing up all the weight steps can lead to really large updates that make the gradient descent diverge. To compensate for this, we'd need to use a quite small learning rate. 

Instead, we can just **divide by the number of records** in our data, $m$ to take the average:

$$E = \frac{1}{2m} \sum_\mu^m \big( y^{\,\mu} - \hat{y}^{\,\mu}\big)^2$$

This way, no matter how much data we use, our **learning rates** will typically be in the range of **0.01** to **0.001**. 

## Gradient Descent Momentum

[Momentum](https://distill.pub/2017/momentum/) is a method to **avoid local minimums** and miss the lowest possible minimum.

## Backpropagation

see also [this interactive description](https://developers-dot-devsite-v2-prod.appspot.com/machine-learning/crash-course/backprop-scroll) of the backpropagation algorithm.

### Calculation of the Error Term with Scalars

Supposed we have a neural network with a **single input layer** $x_1$, **two single hidden layers** $a_1$ and $a_2$ and a **single output layer** $\hat y$ like this:

![backpropagation](images/machine-learning-backpropagation.svg)

Each hidden and output layer has a **sigmoid** function $f$ as an **activation function**.

Let the **error** $E$ and the **loss function** $L$ be

$$
\begin{aligned}
   E &= y - \hat y \\[3pt]
   L &= \frac{1}{2} E^2 = \frac{1}{2} (y - \hat y)^2
\end{aligned}
$$

and let $h_1 = w_1 x_1$, $a_1 = f(h_1)$, $h_2 = w_2 a_1$, $a_2 = f(h_2)$, $h_3 = w_3 a_2$ and $\hat y = f(h_3)$.

We then calculate the gradient of $E$ w.r.t. $w_i$ as follows:

$$
\begin{aligned}
   \frac{\partial L}{\partial w_3} &= \frac{\partial L}{\partial E} \frac{\partial E}{\partial \hat y} \frac{\partial \hat y}{\partial h_3} \frac{\partial h_3}{\partial w_3} \\[3pt]
                                   &= (y - \hat y)(-1)f'(h_3) \, a_2 \\[3pt]
                                   &= \delta_3 a_2 \\[10pt]
   \frac{\partial L}{\partial w_2} &= \frac{\partial L}{\partial E} \frac{\partial E}{\partial \hat y} \frac{\partial \hat y}{\partial h_3} \frac{\partial h_3}{\partial a_2} \frac{\partial a_2}{\partial h_2} \frac{\partial h_2}{\partial w_2} \\[3pt]
                                   &= \delta_3 w_3 f'(h_2) \, a_1 \\[3pt]
                                   &= \delta_2 a_1 \\[10pt]
   \frac{\partial L}{\partial w_1} &= \frac{\partial L}{\partial E} \frac{\partial E}{\partial \hat y} \frac{\partial \hat y}{\partial h_3} \frac{\partial h_3}{\partial a_2} \frac{\partial a_2}{\partial h_2} \frac{\partial h_2}{\partial a_1}  \frac{\partial a_1}{\partial h_1}  \frac{\partial h_1}{\partial w_1}\\[3pt]
                                   &= \delta_2 w_2 f'(h_1) \, x_1 \\[3pt]
                                   &= \delta_1 x_1 \\[10pt]
\end{aligned}
$$

with

$$
\begin{aligned}
  \delta_3 &= -(y - \hat y) \, f'(h_3) = -(y - \hat y) \, \hat y \,(1 - \hat y) \\[3pt]
  {\color{red}\delta}_{\color{red}2} &= {\color{red}\delta}_{\color{red}3} \, {\color{red}w}_{\color{red}3} \, {\color{red}f}'{\color{red}(}{\color{red}h}_{\color{red}2}{\color{red})} = \delta_3 w_3 \, a_2 \, (1 - a_2) \\[3pt]
  \delta_1 &= \delta_2 \, w_2 \, f'(h_1) = \delta_2 \, w_2 \, a_1 \, (1 - a_1) \\[3pt]
\end{aligned}
$$


In order to verify the calculations, we let **PyTorch autograd** calculate the gradients and compare them:

In [2]:
import torch
sigmoid = torch.nn.Sigmoid()

x_1 = torch.tensor([0.5])                         # x_1 = 0.5
y = torch.tensor([1.0])                           # y = 1

w_1 = torch.tensor([1.2], requires_grad=True)     # w_1 = 1.2
w_2 = torch.tensor([1.2], requires_grad=True)     # w_2 = 1.2
w_3 = torch.tensor([1.2], requires_grad=True)     # w_3 = 1.2

h_1 = w_1 * x_1                                   # h_1 = 0.6
a_1 = sigmoid(h_1)                                # a_1 = 0.6457
h_2 = w_2 * a_1                                   # h_2 = 0.7748
a_2 = sigmoid(h_2)                                # a_2 = 0.6846
h_3 = w_3 * a_2                                   # h_3 = 0.8215
y_hat = sigmoid(h_3)                              # y_hat = 0.6945

E = y - y_hat                                     # E = 0.3055
L = 0.5 * E ** 2                                  # L = 0.0467

L.backward()

In [3]:
d_3 = -1 * E * y_hat * (1 - y_hat)
grad_w_3 = d_3 * a_2                              # grad_w_3 = -0.0444
print(grad_w_3.data)

d_2 = d_3 * w_3 * a_2 * (1 - a_2)
grad_w_2 = d_2 * a_1                              # grad_w_2 = -0.0108
print(grad_w_2.data)

d_1 = d_2 * w_2 * a_1 * (1 - a_1)
grad_w_1 = d_1 * x_1                              # grad_w_1 = -0.0023
print(grad_w_1.data)

tensor([-0.0444])
tensor([-0.0108])
tensor([-0.0023])


In [4]:
print(w_3.grad)
print(w_2.grad)
print(w_1.grad)

tensor([-0.0444])
tensor([-0.0108])
tensor([-0.0023])


### Calculation of the Error Term with Tensors

![](images/machine-learning-backprop-tensor.svg)

(the indexes describe <span style="background: #ffff0080;">the layer - not the layer unit</span>)

#### Output Layer

The **error term** $\delta_k$ for the output layer $k$ is

$$\delta_k = -(y - \hat y\,) \, f'(h_k) \qquad \text{with} \; h_k = w_{jk}^\top h_j \quad \text{and} \; f(h_k) = \hat y$$

hence, the **weight change** $\Delta w_{jk}$ is

$$
\begin{aligned}
  \Delta w_{jk} &= \delta_k \, f(h_j) \\[2pt]
                &= (\hat y - y) \, f'(h_k) \, f(h_j)
\end{aligned}
$$

#### Hidden Layer

The **error term** $\delta_j$ for the hidden layer $j$ is

$$\delta_j = w_{jk}^\top \delta_k \, f'(h_j) \qquad \text{with}  \; h_j = w_{ij}^\top h_i$$

hence the **weight change** $\Delta w_{ij}$ is

$$
\begin{aligned}
  \Delta w_{ij} &= \delta_j \, f(h_i) \\[2pt]
                &= w_{jk}^\top \delta_k \, f'(h_j) \, f(h_i)
\end{aligned}
$$

In order to verify the calculations, we let **PyTorch autograd** calculate the gradients and compare them:

In [15]:
import torch
sigmoid = torch.nn.Sigmoid()

x = torch.tensor([0.5, 0.8, 1.2])                      # shape: (3,)
y = torch.tensor([1.0, 0.0])                           # shape: (2,)

w_1 = torch.ones((3, 3), requires_grad=True)           # shape: (3,3)
w_2 = torch.ones((3, 2), requires_grad=True)           # shape: (3,2)
w_3 = torch.ones((2, 2), requires_grad=True)           # shape: (2,2)

h_1 = w_1.T.mv(x)                                      # shape: (3,)                       h_1   = [2.5, 2.5, 2.5]
a_1 = sigmoid(h_1)                                     # shape: (3,)                       a_1   = [0.9241, 0.9241, 0.9241]
h_2 = w_2.T.mv(a_1)                                    # shape: (2,)                       h_2   = [2.7724, 2.7724]
a_2 = sigmoid(h_2)                                     # shape: (2,)                       a_2   = [0.9412, 0.9412]
h_3 = w_3.T.mv(a_2)                                    # shape: (2,)                       h_3   = [1.8823, 1.8823]
y_hat = sigmoid(h_3)                                   # shape: (2,)                       y_hat = [0.8679, 0.8679]

E = y - y_hat                                          # shape: (2,)                       E     = [0.1321, -0.8679]
L = 0.5 * E.dot(E)                                     # shape: ()                         L     = [0.3853]

L.backward()

In [23]:
# delta_3
d_3 = -1 * E * y_hat * (1 - y_hat)                     # shape: (2,)                                 d_3 = [-0.0151, 0.0995]
grad_w_3 = (d_3.view(-1, 1) @ a_2.view(1, -1)).T       # shape: (2,1) @ (1,2) -> (2,2) -> (2,2)
print(grad_w_3.data)

d_2 = d_3 @ w_3.T * a_2 * (1 - a_2)                    # shape: (2,)                                 d_2 = [0.0047, 0.0047]
grad_w_2 = (d_2.view(-1, 1) @ a_1.view(1, -1)).T       # shape: (2,1) @ (1,3) -> (2,3) -> (3,2)
print(grad_w_2.data)

d_1 = d_2 @ w_2.T * a_1 * (1 - a_1)                    # shape: (3,)                                 d_1 = [0.0007, 0.0007, 0.0007]
grad_w_1 = (d_1.view(-1, 1) * x.view(1, -1)).T         # shape: (3,1) @ (1,3) -> (3,3) -> (3,3)
print(grad_w_1.data)

tensor([[-0.0143,  0.0937],
        [-0.0143,  0.0937]])
tensor([[0.0043, 0.0043],
        [0.0043, 0.0043],
        [0.0043, 0.0043]])
tensor([[0.0003, 0.0003, 0.0003],
        [0.0005, 0.0005, 0.0005],
        [0.0008, 0.0008, 0.0008]])


In [24]:
print(w_3.grad)
print(w_2.grad)
print(w_1.grad)

tensor([[-0.0143,  0.0937],
        [-0.0143,  0.0937]])
tensor([[0.0043, 0.0043],
        [0.0043, 0.0043],
        [0.0043, 0.0043]])
tensor([[0.0003, 0.0003, 0.0003],
        [0.0005, 0.0005, 0.0005],
        [0.0008, 0.0008, 0.0008]])


## Convolutions

In machine learning **convolution** is a mathematical operation on two discrete functions (an input $\text{I}$ and a kernel $\text{K}$) that produces a third discrete function (an output $\text{O}$) expressing how the shape of $\text{I}$ is modified by $\text{K}$:

$$\text{I} \ast \text{K} =  \text{O}$$

Computing the inverse of the convolution operation is known as **deconvolution**: finding an input $\text{I}$ that satisfies the equation $\text{I} \ast \text{K} =  \text{O}$.

The term **transposed convolution** describes exactly what a standard convolutional layer does, but on a **modified input** feature map.

### Convolutional Layer

A **standard convolution** is typically used for **downsampling** a given input. 

The convolutional layer of an **input** of size $i \times i$ is defined by the parameters:

1. **Padding** $p$: The amount of zeros padded around the original input increasing the size to $(i+2p) \times (i+2p)$
2. **Stride** $s$: The amount by which the kernel is shifted when sliding across the input image.
3. **Insertions** $z$: filling the layer with zeros. For convolutions there is no filling: $z=0$.

For a given size of input $i$, kernel $k$, padding $p$ and stride $s$, the size of the output feature map $o \times o$ is given by

$$o = \frac{i + 2p - k}{s} + 1$$

In [26]:
import torch
import torch.nn as nn

conv = nn.Conv2d(1, 1, 3, stride=3, padding=1)      # k=3, s=3, p=1
x = torch.ones(1, 1, 10, 10)                        # i=10  

conv(x).squeeze(0).squeeze(0).shape                 # squeeze away batch- and color-depth dimensions

torch.Size([4, 4])

### Transposed Convolutional Layer

**Transposed convolutions** are used for **upsampling** a given input (which is typically the output of a standard convolution).

A transposed convolutional layer is also defined by the padding and stride. These values of padding and stride are the one that hypothetically were carried out on the output to generate the input: if you take the output, and carry out a standard convolution with stride and padding defined, it will generate the spatial dimension same as that of the input.

For a transposed convolutional layer of an **input** size $i \times i$, we calculate:

1. **Padding** $p\,' = k - p - 1$
2. **Stride** $s\,' = 1$
3. **Insertions** $z = s -1 $

For a given size of input $i$, kernel $k$, padding $p$ and stride $s$, the size of the output feature map $o \times o$ generated is given by

$$o = (i-1) \cdot s + k - 2p$$

#### Example

Image Source: [Animation for Convolutional layers](https://github.com/thomd/conv_layers_animation)

<img src="images/t_conv_K3S2P1.gif" width="500" style="float:left"/>
<img src="images/t_conv_K3S3P1.gif" width="500" style="float:left"/>
<img src="images/t_conv_K3S4P1.gif" width="500" style="float:left"/>
<img src="images/t_conv_K3S2P0.gif" width="500" style="float:left"/>

In [32]:
import torch
import torch.nn as nn

t_conv = nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1)      # k=3, s=2, p=1
x = torch.ones(1, 1, 3, 3)                                     # i=3

t_conv(x).squeeze(0).squeeze(0).shape                          # squeeze away batch- and color-depth dimensions

torch.Size([5, 5])

## Gram Matrix

The **Gram matrix** $G$ of a set of vectors $a_1, \dots ,a_n$ is the Hermitian matrix of **inner products** (or **dot products**), whose entries $g_{ij}$ are given by

$$g_{ij} = a_i \cdot a_j$$

if vectors $a_1, \dots ,a_n$ are **columns** of a **matrix** $A$, then

$$G = A^\top \cdot A$$

A Gram matrix is **Positive Definite** and **Symmetric**

### Intuition

The dot product $\vec{a} \cdot \vec{b} = \vert a \vert \vert b \vert \cos(\theta)$ can be seen as **how similar two vectors** actually are.

### Example

Let 

$$\vec{a}_1 = \begin{pmatrix}a_{11}\\a_{21}\\a_{31}\\a_{41}\\\end{pmatrix} = \begin{pmatrix}1\\2\\3\\4\\\end{pmatrix} \; \text{and} \;\; \vec{a}_2 = \begin{pmatrix}a_{21}\\a_{22}\\a_{32}\\a_{42}\\\end{pmatrix} = \begin{pmatrix}2\\3\\4\\5\\\end{pmatrix}$$

then the Gram Matrix calculates as

$$G(\vec{a}_1, \vec{a}_2) = (\vec{a}_1, \vec{a}_2)^\top \cdot (\vec{a}_1, \vec{a}_2) = \begin{pmatrix} \vec{a}_1 \\ \vec{a}_2 \end{pmatrix} \cdot (\vec{a}_1, \vec{a}_2) = \begin{pmatrix}\vec{a}_1 \cdot \vec{a}_1 & \vec{a}_1 \cdot \vec{a}_2\\\vec{a}_2 \cdot \vec{a}_1 & \vec{a}_2 \cdot \vec{a}_2\end{pmatrix} = \begin{pmatrix}30 & 40\\40 & 54\end{pmatrix}$$

In [73]:
import numpy as np
a1 = np.array([1, 2, 3, 4])
a2 = np.array([2, 3, 4, 5])

A = np.column_stack((a1, a2))    # column_stack(): vectors are columns
A

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [74]:
G = np.matmul(A.T, A)
G

array([[30, 40],
       [40, 54]])

### Gram Matrix in Convolutional Layers

In machine learning, a specific **convolutions layer** $l$ with $N_l$ distinct **filters** has $N_l$ **vectorized feature maps** each of size $M_l = w \cdot h$ with $w$ and $h$ the width and height of the input image (hence number of pixels). A convolutional layer can hence be described as a matrix $F^l \in \textbf{R}^{N_l \times M_l}$.

**Feature correlations** are given by the **Gram matric** $G^l \in \textbf{R}^{N_l \times N_l}$, where $G_{ij}^l$ is the inner product between the vectorized feature maps $i$ and $j$ in layer $l$:

$$G_{ij}^l = \sum_{k=1}^{M_l} F_{ik}^l F_{jk}^l \tag{1}$$

### Intuition

The gram matrix describe the **correlation** or **similarity** between $N_l$ **filters** of an convolutional layer $l$ if we consider the feature map as $N_l$ filters $K$ applied to a vectorized input image of size $M_l$.

The formula for gram matrix (1) reminds to the calculation of a **correlation** $r$ except that we dont substract the mean and don't divide by the vector lengths:

$$r = \frac{\sum_i (x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum_i (x_i - \bar{x})^2} \sqrt{\sum_i (y_i - \bar{y})^2}}$$

### Example with PyTorch

Using the example above, we have two vectorized filter maps $\vec{a}_i$ of a $2 \times 2$ image, hence a convolutional layer 

$$F = (\vec{a}_1, \vec{a}_2) = \begin{pmatrix}1 & 2\\2 & 3\\3 & 4\\4 & 5\\\end{pmatrix}$$

In [117]:
import torch

def gram_matrix(tensor):
    """ Calculate the Gram Matrix of a given tensor 
        Gram Matrix: https://en.wikipedia.org/wiki/Gramian_matrix
    """
    
    # get the batch_size, depth, height, and width of the Tensor
    _, d, h, w = tensor.size()
    
    # vectorize the feature map
    tensor = tensor.view(d, h * w)

    # calculate the gram matrix
    gram = torch.mm(tensor, tensor.t())
    
    return gram

In [119]:
a1 = torch.tensor([1, 2, 3, 4]).view(2,2)
a2 = torch.tensor([2, 3, 4, 5]).view(2,2)

A = torch.stack((a1, a2), dim=0)                 # dim=1: row stack
print(A)

A = A[None,:]                                    # add batch dimension
print(A.shape)

gram_matrix(A)

tensor([[[1, 2],
         [3, 4]],

        [[2, 3],
         [4, 5]]])
torch.Size([1, 2, 2, 2])


tensor([[30, 40],
        [40, 54]])